name: "MPP Solar Monitor"
description: "Monitor MPP Solar PIP5048MG inverter and publish data to MQTT"
version: "1.0.8"
slug: "mpp_solar"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
stage: stable
homeassistant: 2021.8.0
options:
  device: "/dev/hidraw0"
  interval: 5
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  mqtt_topic: "mpp_solar"
  debug: true
schema:
  device: str
  interval: int(2,300)
  mqtt_host: str
  mqtt_port: port
  mqtt_username: str?
  mqtt_password: password?
  mqtt_topic: str
  debug: bool
devices:
  - /dev/hidraw0
  - /dev/hidraw1
  - /dev/hidraw2
  - /dev/hidraw3
services:
  - mqtt:want
privileged:
  - SYS_ADMIN
full_access: true